name: Bug Report
description: File a bug report
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: Please describe what the feature does. You’ll be asked why it is important later.
      placeholder: A clear and concise description of this feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?
      description: A clear and concise description of what you want to happen, the importance of the feature, and the impact it should have on your project.
    validations:
      required: true
  - type: input
    attributes:
      label: Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?
      description: A brief description of alternatives that might exist, if you can think of any, and how your project will be affected if the feature cannot be implemented.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.
      description: URLs, screenshots, or any other examples of this feature in other projects
    validations:
      required: true
  - type: textarea
    attributes:
        label: Additional information
        description: Any additional information or comments
    validations:
        required: false
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
